In [1]:
#Imports

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [5]:
#Series 2 of RCFD, could've been any of the file


rcfd_data_2 = pd.read_csv(r'..\data\manual\dycfrwcdm9puanhs.csv') #series 2 of rcfd

In [6]:
#Asset Level

asset_level_0 = rcfd_data_2[['RSSD9001','RSSD9017','RSSD9999','RCFD2170']]
asset_level_0 = asset_level_0.fillna(0)
filtered_asset_level_0 = asset_level_0[asset_level_0['RSSD9999'] == '03/31/2022']
filtered_asset_level_0

RSSD9001                          RSSD9017    RSSD9999  RCFD2170
0            37            BANK OF HANCOCK COUNTY  03/31/2022       0.0
5           242  FIRST COMMUNITY BANK XENIA-FLORA  03/31/2022       0.0
10          279       MINEOLA COMMUNITY BANK, SSB  03/31/2022       0.0
15          354                  BISON STATE BANK  03/31/2022       0.0
20          457                  LOWRY STATE BANK  03/31/2022       0.0
...         ...                               ...         ...       ...
23870   5620869                      GENESIS BANK  03/31/2022       0.0
23875   5650923                    WATERFALL BANK  03/31/2022       0.0
23880   5660146                         ENTREBANK  03/31/2022       0.0
23885   5673191                     LOCALITY BANK  03/31/2022       0.0
23894   5691319         SCOTTSDALE COMMUNITY BANK  03/31/2022       0.0

[4844 rows x 4 columns]

In [7]:
#other_series that Jeremy provided with RSSD9010

other_data = pd.read_csv(r'..\data\manual\nw5crmbtaa03thi9.csv') 

In [8]:
#I already queried the data to have the date March 31st 2022. 

#Variables: BHCT2170, BHSP2170, BHCP2170, BHCA2170 are all total assets from different times to current(I filled in NAs with 0)

#I combined all the total assets in order for all GSIB to have some value
other_data = other_data.fillna(0)
other_data['Total Asset'] = other_data['BHCT2170'] + other_data['BHSP2170'] + other_data['BHCP2170'] + other_data['BHCA2170']

In [9]:
other_df = other_data[['RSSD9001', 'RSSD9999', 'RSSD9017', 'RSSD9010', 'Total Asset']]
other_df

RSSD9001    RSSD9999                                RSSD9017  \
0     1020180  2022-03-31            BREMER FINANCIAL CORPORATION   
1     1020201  2022-03-31                           HSBC USA INC.   
2     1020902  2022-03-31        FIRST NATIONAL OF NEBRASKA, INC.   
3     1022764  2022-03-31         CENTRAL PACIFIC FINANCIAL CORP.   
4     1023220  2022-03-31  B.N.Y. HOLDINGS (DELAWARE) CORPORATION   
..        ...         ...                                     ...   
427   5375459  2022-03-31           EB ACQUISITION COMPANY II LLC   
428   5478903  2022-03-31                               CSBH, LLC   
429   5530258  2022-03-31                 CARTER BANKSHARES, INC.   
430   5559343  2022-03-31              AMALGAMATED FINANCIAL CORP   
431   5586871  2022-03-31                 SOFI TECHNOLOGIES, INC.   

                  RSSD9010  Total Asset  
0         BREMER FNCL CORP   17706989.0  
1                 HSBC USA   34557478.0  
2          FIRST NAT OF NE   30654054.0  
3       CENTRAL PACIFIC FC    7898682.0  
4         BNY HOLD DE CORP      93688.0  
..                     ...          ...  
427       EB ACQ CO II LLC   19945808.0  
428               CSBH LLC     151534.0  
429           CARTER BSHRS     359834.0  
430  AMALGAMATED FNCL CORP    8271968.0  
431             SOFI TECHS   18987079.0  

[432 rows x 5 columns]

In [10]:
#GSIB list with all different versions of each big bank(26 banks)

GSIB_list = ['JPMORGAN CHASE & CO', 'JPMORGAN CHASE HOLDS LLC', 'BANK OF AMER CORP', 'BANK OF NY MELLON CORP', 'CITIGROUP', 'CITICORP LLC',
'HSBC USA', 'HSBC N AMER HOLDS', 'BARCLAYS GROUP US', 'BARCLAYS US LLC', 'BNP PARIBAS USA', 'DEUTSCHE BK TR CORP', 'GOLDMAN SACHS GROUP THE', 'MUFG AMERS HOLDS CORP', 'UBS AMERS HOLD LLC', 'MIZUHO AMERS LLC', 'MORGAN STANLEY', 'MORGAN STANLEY DOMESTIC HOLD', 'MORGAN STANLEY CAP MGMT LLC', 'RBC USA HOLDCO CORP', 'RBC US GRP HOLDS LLC', 'SANTANDER HOLDS USA', 'STATE STREET CORP', 'WELLS FARGO & CO', 'TD GRP US HOLDS LLC', 'TD BK US HC']

In [11]:
GSIB_list

['JPMORGAN CHASE & CO',
 'JPMORGAN CHASE HOLDS LLC',
 'BANK OF AMER CORP',
 'BANK OF NY MELLON CORP',
 'CITIGROUP',
 'CITICORP LLC',
 'HSBC USA',
 'HSBC N AMER HOLDS',
 'BARCLAYS GROUP US',
 'BARCLAYS US LLC',
 'BNP PARIBAS USA',
 'DEUTSCHE BK TR CORP',
 'GOLDMAN SACHS GROUP THE',
 'MUFG AMERS HOLDS CORP',
 'UBS AMERS HOLD LLC',
 'MIZUHO AMERS LLC',
 'MORGAN STANLEY',
 'MORGAN STANLEY DOMESTIC HOLD',
 'MORGAN STANLEY CAP MGMT LLC',
 'RBC USA HOLDCO CORP',
 'RBC US GRP HOLDS LLC',
 'SANTANDER HOLDS USA',
 'STATE STREET CORP',
 'WELLS FARGO & CO',
 'TD GRP US HOLDS LLC',
 'TD BK US HC']

In [12]:
#Filtered df

df = pd.DataFrame(GSIB_list)

filtered_df = other_df[other_df['RSSD9010'].isin(GSIB_list)]
filtered_df

RSSD9001    RSSD9999                                  RSSD9017  \
1     1020201  2022-03-31                             HSBC USA INC.   
17    1032473  2022-03-31           DEUTSCHE BANK TRUST CORPORATION   
19    1039502  2022-03-31                      JPMORGAN CHASE & CO.   
51    1073757  2022-03-31               BANK OF AMERICA CORPORATION   
90    1111435  2022-03-31                  STATE STREET CORPORATION   
101   1120754  2022-03-31                     WELLS FARGO & COMPANY   
173   1249196  2022-03-31                TD BANK US HOLDING COMPANY   
178   1378434  2022-03-31        MUFG AMERICAS HOLDINGS CORPORATION   
200   1575569  2022-03-31                     BNP PARIBAS USA, INC.   
211   1951350  2022-03-31                            CITIGROUP INC.   
231   2162966  2022-03-31                            MORGAN STANLEY   
248   2380443  2022-03-31            GOLDMAN SACHS GROUP, INC., THE   
290   2914521  2022-03-31                    BARCLAYS GROUP US INC.   
313   3226762  2022-03-31                RBC USA HOLDCO CORPORATION   
314   3232316  2022-03-31          HSBC NORTH AMERICA HOLDINGS INC.   
323   3375370  2022-03-31                              CITICORP LLC   
333   3587146  2022-03-31  BANK OF NEW YORK MELLON CORPORATION, THE   
337   3606542  2022-03-31                  TD GROUP US HOLDINGS LLC   
353   3820272  2022-03-31    MORGAN STANLEY DOMESTIC HOLDINGS, INC.   
354   3820290  2022-03-31    MORGAN STANLEY CAPITAL MANAGEMENT, LLC   
385   3981856  2022-03-31              SANTANDER HOLDINGS USA, INC.   
410   4846998  2022-03-31                  UBS AMERICAS HOLDING LLC   
415   5006575  2022-03-31                           BARCLAYS US LLC   
417   5034792  2022-03-31                       MIZUHO AMERICAS LLC   
418   5064641  2022-03-31               JPMORGAN CHASE HOLDINGS LLC   
423   5280254  2022-03-31                 RBC US GROUP HOLDINGS LLC   

                         RSSD9010   Total Asset  
1                        HSBC USA  3.455748e+07  
17            DEUTSCHE BK TR CORP  1.079900e+07  
19            JPMORGAN CHASE & CO  4.514488e+09  
51              BANK OF AMER CORP  3.786643e+09  
90              STATE STREET CORP  3.654620e+08  
101              WELLS FARGO & CO  2.315346e+09  
173                   TD BK US HC  5.120087e+07  
178         MUFG AMERS HOLDS CORP  1.828843e+08  
200               BNP PARIBAS USA  1.806426e+08  
211                     CITIGROUP  2.786665e+09  
231                MORGAN STANLEY  1.584907e+09  
248       GOLDMAN SACHS GROUP THE  2.038128e+09  
290             BARCLAYS GROUP US  2.648400e+07  
313           RBC USA HOLDCO CORP  2.358245e+07  
314             HSBC N AMER HOLDS  2.592476e+08  
323                  CITICORP LLC  3.817940e+08  
333        BANK OF NY MELLON CORP  5.466460e+08  
337           TD GRP US HOLDS LLC  5.766197e+08  
353  MORGAN STANLEY DOMESTIC HOLD  1.601710e+08  
354   MORGAN STANLEY CAP MGMT LLC  6.627390e+07  
385           SANTANDER HOLDS USA  1.861075e+08  
410            UBS AMERS HOLD LLC  2.683296e+08  
415               BARCLAYS US LLC  1.987650e+08  
417              MIZUHO AMERS LLC  5.800320e+07  
418      JPMORGAN CHASE HOLDS LLC  2.357430e+08  
423          RBC US GRP HOLDS LLC  2.040902e+08

In [13]:
#Add the banks from the RCFD that aren't in filtered_df

x = [925411, 1015560, 655839]

RCFD_GSIB = filtered_asset_level_0[['RSSD9001', 'RSSD9999', 'RSSD9017', 'RCFD2170']]
R_gsib = RCFD_GSIB[RCFD_GSIB['RSSD9001'].isin(x)]
R_gsib.rename(columns={'RCFD2170': 'Total Asset'}, inplace=True)
R_gsib

RSSD9001    RSSD9999  \
12367    655839  03/31/2022   
17688    925411  03/31/2022   
19537   1015560  03/31/2022   

                                                RSSD9017  Total Asset  
12367                                 CCB COMMUNITY BANK          0.0  
17688        SUMITOMO MITSUI TRUST BANK (U.S.A.) LIMITED          0.0  
19537  INDUSTRIAL AND COMMERCIAL BANK OF CHINA (USA),...          0.0

In [14]:
#29 banks using other_series as main source of GSIB banks(RSSD9001 don't match together with RCFD)

#filtered_df.drop(columns=['RSSD9010'], inplace=True)
stacked_df = pd.concat([filtered_df, R_gsib], ignore_index=True)
stacked_df

RSSD9001    RSSD9999                                           RSSD9017  \
0    1020201  2022-03-31                                      HSBC USA INC.   
1    1032473  2022-03-31                    DEUTSCHE BANK TRUST CORPORATION   
2    1039502  2022-03-31                               JPMORGAN CHASE & CO.   
3    1073757  2022-03-31                        BANK OF AMERICA CORPORATION   
4    1111435  2022-03-31                           STATE STREET CORPORATION   
5    1120754  2022-03-31                              WELLS FARGO & COMPANY   
6    1249196  2022-03-31                         TD BANK US HOLDING COMPANY   
7    1378434  2022-03-31                 MUFG AMERICAS HOLDINGS CORPORATION   
8    1575569  2022-03-31                              BNP PARIBAS USA, INC.   
9    1951350  2022-03-31                                     CITIGROUP INC.   
10   2162966  2022-03-31                                     MORGAN STANLEY   
11   2380443  2022-03-31                     GOLDMAN SACHS GROUP, INC., THE   
12   2914521  2022-03-31                             BARCLAYS GROUP US INC.   
13   3226762  2022-03-31                         RBC USA HOLDCO CORPORATION   
14   3232316  2022-03-31                   HSBC NORTH AMERICA HOLDINGS INC.   
15   3375370  2022-03-31                                       CITICORP LLC   
16   3587146  2022-03-31           BANK OF NEW YORK MELLON CORPORATION, THE   
17   3606542  2022-03-31                           TD GROUP US HOLDINGS LLC   
18   3820272  2022-03-31             MORGAN STANLEY DOMESTIC HOLDINGS, INC.   
19   3820290  2022-03-31             MORGAN STANLEY CAPITAL MANAGEMENT, LLC   
20   3981856  2022-03-31                       SANTANDER HOLDINGS USA, INC.   
21   4846998  2022-03-31                           UBS AMERICAS HOLDING LLC   
22   5006575  2022-03-31                                    BARCLAYS US LLC   
23   5034792  2022-03-31                                MIZUHO AMERICAS LLC   
24   5064641  2022-03-31                        JPMORGAN CHASE HOLDINGS LLC   
25   5280254  2022-03-31                          RBC US GROUP HOLDINGS LLC   
26    655839  03/31/2022                                 CCB COMMUNITY BANK   
27    925411  03/31/2022        SUMITOMO MITSUI TRUST BANK (U.S.A.) LIMITED   
28   1015560  03/31/2022  INDUSTRIAL AND COMMERCIAL BANK OF CHINA (USA),...   

                        RSSD9010   Total Asset  
0                       HSBC USA  3.455748e+07  
1            DEUTSCHE BK TR CORP  1.079900e+07  
2            JPMORGAN CHASE & CO  4.514488e+09  
3              BANK OF AMER CORP  3.786643e+09  
4              STATE STREET CORP  3.654620e+08  
5               WELLS FARGO & CO  2.315346e+09  
6                    TD BK US HC  5.120087e+07  
7          MUFG AMERS HOLDS CORP  1.828843e+08  
8                BNP PARIBAS USA  1.806426e+08  
9                      CITIGROUP  2.786665e+09  
10                MORGAN STANLEY  1.584907e+09  
11       GOLDMAN SACHS GROUP THE  2.038128e+09  
12             BARCLAYS GROUP US  2.648400e+07  
13           RBC USA HOLDCO CORP  2.358245e+07  
14             HSBC N AMER HOLDS  2.592476e+08  
15                  CITICORP LLC  3.817940e+08  
16        BANK OF NY MELLON CORP  5.466460e+08  
17           TD GRP US HOLDS LLC  5.766197e+08  
18  MORGAN STANLEY DOMESTIC HOLD  1.601710e+08  
19   MORGAN STANLEY CAP MGMT LLC  6.627390e+07  
20           SANTANDER HOLDS USA  1.861075e+08  
21            UBS AMERS HOLD LLC  2.683296e+08  
22               BARCLAYS US LLC  1.987650e+08  
23              MIZUHO AMERS LLC  5.800320e+07  
24      JPMORGAN CHASE HOLDS LLC  2.357430e+08  
25          RBC US GRP HOLDS LLC  2.040902e+08  
26                           NaN  0.000000e+00  
27                           NaN  0.000000e+00  
28                           NaN  0.000000e+00

In [15]:
#Combined Total Assets(Seems kind of high)

stacked_df['Total Asset'].sum()

21043580255.0

In [16]:
#In comparison to all exisiting GSIB banks in RCFD already(37)

bank_numbers = [
    651448, 852218, 480228, 1443266, 476810, 413208, 3357620, 1015560, 2980209,
    214807, 304913, 670560, 2325882, 3066025, 2182786, 3212149, 541101, 934329,
    398668, 488318, 229913, 1456501, 2489805, 3783948, 722777, 35301, 812164,
    93619, 352745, 925411, 497404, 2121196, 2362458, 2531991, 451965, 688079,
    1225761
]

filtered_asset_level_0
Rcfd_gsib = filtered_asset_level_0[filtered_asset_level_0['RSSD9001'].isin(bank_numbers)]
Rcfd_gsib

RSSD9001                                           RSSD9017  \
635       35301                STATE STREET BANK AND TRUST COMPANY   
1736      93619  STATE STREET BANK AND TRUST COMPANY, NATIONAL ...   
3918     214807               DEUTSCHE BANK TRUST COMPANY AMERICAS   
4163     229913                                  MIZUHO BANK (USA)   
5696     304913               DEUTSCHE BANK TRUST COMPANY DELAWARE   
6547     352745                STATE STREET BANK AND TRUST COMPANY   
7441     398668  BANK OF NEW YORK MELLON TRUST COMPANY, NATIONA...   
7740     413208                HSBC BANK USA, NATIONAL ASSOCIATION   
8441     451965             WELLS FARGO BANK, NATIONAL ASSOCIATION   
8949     476810                                     CITIBANK, N.A.   
9047     480228              BANK OF AMERICA, NATIONAL ASSOCIATION   
9201     488318                       BNY MELLON TRUST OF DELAWARE   
9356     497404                                      TD BANK, N.A.   
10200    541101                       BANK OF NEW YORK MELLON, THE   
12274    651448                      JPMORGAN CHASE BANK, DEARBORN   
12687    670560               DEUTSCHE BANK NATIONAL TRUST COMPANY   
13027    688079    WELLS FARGO TRUST COMPANY, NATIONAL ASSOCIATION   
13651    722777               SANTANDER BANK, NATIONAL ASSOCIATION   
15351    812164  STATE STREET BANK AND TRUST COMPANY OF CALIFOR...   
16194    852218          JPMORGAN CHASE BANK, NATIONAL ASSOCIATION   
17688    925411        SUMITOMO MITSUI TRUST BANK (U.S.A.) LIMITED   
17885    934329                   BNY MELLON, NATIONAL ASSOCIATION   
19537   1015560  INDUSTRIAL AND COMMERCIAL BANK OF CHINA (USA),...   
19750   1225761                     WELLS FARGO NATIONAL BANK WEST   
19877   1443266   BANK OF AMERICA CALIFORNIA, NATIONAL ASSOCIATION   
19897   1456501                          MORGAN STANLEY BANK, N.A.   
20170   2121196                  TD BANK USA, NATIONAL ASSOCIATION   
20215   2182786                             GOLDMAN SACHS BANK USA   
20298   2325882  DEUTSCHE BANK TRUST COMPANY, NATIONAL ASSOCIATION   
20387   2362458  WELLS FARGO BANK SOUTH CENTRAL, NATIONAL ASSOC...   
20472   2489805  MORGAN STANLEY PRIVATE BANK, NATIONAL ASSOCIATION   
20536   2531991  WELLS FARGO DELAWARE TRUST COMPANY, NATIONAL A...   
21696   2980209                             BARCLAYS BANK DELAWARE   
21863   3066025  GOLDMAN SACHS TRUST COMPANY, NATIONAL ASSOCIAT...   
22129   3212149                                       UBS BANK USA   
22625   3357620  HSBC TRUST COMPANY (DELAWARE), NATIONAL ASSOCI...   
23501   3783948           RBC BANK (GEORGIA), NATIONAL ASSOCIATION   

         RSSD9999      RCFD2170  
635    03/31/2022  3.184940e+08  
1736   03/31/2022  3.793300e+04  
3918   03/31/2022  0.000000e+00  
4163   03/31/2022  6.967587e+06  
5696   03/31/2022  0.000000e+00  
6547   03/31/2022  0.000000e+00  
7441   03/31/2022  1.451176e+06  
7740   03/31/2022  1.747204e+08  
8441   03/31/2022  1.764272e+09  
8949   03/31/2022  1.718008e+09  
9047   03/31/2022  2.513619e+09  
9201   03/31/2022  1.970470e+05  
9356   03/31/2022  4.173584e+08  
10200  03/31/2022  3.804650e+08  
12274  03/31/2022  6.193200e+04  
12687  03/31/2022  0.000000e+00  
13027  03/31/2022  1.297971e+06  
13651  03/31/2022  9.590397e+07  
15351  03/31/2022  7.941000e+03  
16194  03/31/2022  3.476711e+09  
17688  03/31/2022  0.000000e+00  
17885  03/31/2022  3.464100e+07  
19537  03/31/2022  0.000000e+00  
19750  03/31/2022  1.949569e+07  
19877  03/31/2022  2.985500e+07  
19897  03/31/2022  2.017370e+08  
20170  03/31/2022  0.000000e+00  
20215  03/31/2022  4.746430e+08  
20298  03/31/2022  0.000000e+00  
20387  03/31/2022  8.537660e+06  
20472  03/31/2022  2.035080e+08  
20536  03/31/2022  2.329590e+05  
21696  03/31/2022  0.000000e+00  
21863  03/31/2022  1.084690e+05  
22129  03/31/2022  0.000000e+00  
22625  03/31/2022  0.000000e+00  
23501  03/31/2022  0.000000e+00

In [20]:
#Cut all the banks that have RCFD2170 of 0, you are left with 25 banks

Rcfd_gsib = Rcfd_gsib[Rcfd_gsib['RCFD2170'] != 0]
Rcfd_gsib['RSSD9001'].tolist()

[35301,
 93619,
 229913,
 398668,
 413208,
 451965,
 476810,
 480228,
 488318,
 497404,
 541101,
 651448,
 688079,
 722777,
 812164,
 852218,
 934329,
 1225761,
 1443266,
 1456501,
 2182786,
 2362458,
 2489805,
 2531991,
 3066025]

In [18]:
#Total Assets of 25 banks

Rcfd_gsib['RCFD2170'].sum()

11842332171.0

The original RCFD data had these banks(I checked multiple times:)

Banks and their RSSD9001:

JPMorgan Chase - 651448
JPMORGAN CHASE BANK, NATIONAL ASSOCIATION - 852218
Bank of America, National Association - 480228
BANK OF AMERICA CALIFORNIA, NATIONAL ASSOCIATION - 1443266
CITIBANK, N.A. - 476810
HSBC BANK USA, NATIONAL ASSOCIATION - 413208
HSBC TRUST COMPANY (DELAWARE), NATIONAL ASSOCIATION - 3357620
INDUSTRIAL AND COMMERCIAL BANK OF CHINA (USA), NATIONAL ASSOCIATION - 1015560
BARCLAYS BANK DELAWARE - 2980209


No Bank of China, Agricultural Bank of China, BNP Paribas, China Construction Bank, No bank of communication, Groupe BPCE, Groupe Crédit Agricole, ING, Société Générale, Standard Chartered, 

DEUTSCHE BANK TRUST COMPANY AMERICAS - 214807
DEUTSCHE BANK TRUST COMPANY DELAWARE - 304913
DEUTSCHE BANK NATIONAL TRUST COMPANY - 670560
DEUTSCHE BANK TRUST COMPANY, NATIONAL ASSOCIATION - 2325882
GOLDMAN SACHS TRUST COMPANY, NATIONAL ASSOCIATION, THE - 3066025
GOLDMAN SACHS BANK USA - 2182786
UBS BANK USA - 3212149
BANK OF NEW YORK MELLON, THE - 541101
BNY MELLON, NATIONAL ASSOCIATION - 934329
BANK OF NEW YORK MELLON TRUST COMPANY, NATIONAL ASSOCIATION, THE - 398668
BNY MELLON TRUST OF DELAWARE - 488318
MIZUHO BANK (USA) - 229913
MORGAN STANLEY BANK, N.A. - 1456501
MORGAN STANLEY PRIVATE BANK, NATIONAL ASSOCIATION - 2489805
RBC BANK (GEORGIA), NATIONAL ASSOCIATION - 3783948
SANTANDER BANK, NATIONAL ASSOCIATION - 722777
STATE STREET BANK AND TRUST COMPANY - 35301
STATE STREET BANK AND TRUST COMPANY OF CALIFORNIA, NATIONAL ASSOCIATION - 812164
STATE STREET BANK AND TRUST COMPANY, NATIONAL ASSOCIATION - 93619
STATE STREET BANK AND TRUST COMPANY - 352745
SUMITOMO MITSUI TRUST BANK (U.S.A.) LIMITED - 925411
TD BANK, N.A. - 497404
TD BANK USA, NATIONAL ASSOCIATION - 2121196
WELLS FARGO BANK SOUTH CENTRAL, NATIONAL ASSOCIATION - 2362458
WELLS FARGO DELAWARE TRUST COMPANY, NATIONAL ASSOCIATION - 2531991
WELLS FARGO BANK, NATIONAL ASSOCIATION - 451965
WELLS FARGO TRUST COMPANY, NATIONAL ASSOCIATION - 688079
WELLS FARGO NATIONAL BANK WEST - 1225761


Other Series

Contains BNP Paribas, and Barclays Group instead of specifically Barclays Delaware. In addition to RBC US and USA instead of RBC Georgia and other exampes like HSBC USA instead of HSBC Delaware. Could be maybe helpful cause these have asset values instead of 0s.